# Generated by Django 5.0 on 2023-12-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
